# -------------------------------
# 
# 公共设置
#
# -------------------------------

# 站点设置
title: Kinddom
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ouyangyewei.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_nav: "#666666" #"#FF3333" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"



# -------------------------------
# 
# 联系方式设置
#
# -------------------------------

# 主页的格言
aphorism: “每一天，每一年，都可以是新的起跑线”

# 社交链接
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# 地址信息
address:
  - lines: 
    - 广东省, 佛山市
    - 顺德区, 均安镇
email: ouyangyewei@foxmail.com
tel: 13545095922



# -------------------------------
# 
# 基础数据设置
#
# -------------------------------

# 产品简介
products:
  - name: Mark Webber
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    url: "http://www.baidu.com"
  - name: Paul Jameson
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    url: "http://www.baidu.com"
  - name: Laura Sommers
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    url: "http://www.baidu.com"
  - name: Martin Blunt
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    url: "http://www.baidu.com"
  - name: Martin Blunt
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    url: "http://www.baidu.com"
  - name: Martin Blunt
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    url: "http://www.baidu.com"
  - name: Martin Blunt
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    url: "http://www.baidu.com"

# 友情链接
clients:
  - name: amazon
    img: client01.png
    url: http://www.amazon.co.uk/shops/A3NVU9AA0XWIL
  - name: wish
    img: client02.png
    url: http://www.wish.com

# 关于我们
about: "Kinddom是一家负责对外贸易的产品介绍网站, 期待与您合作."

# 品牌故事
brandStory: “如果不去西西里，就像没有到过意大利，因为在西西里你才能找到意大利的美丽之源。” 西西里岛在历史上命运多舛，曾经被希腊人、西班牙人、阿拉伯人和诺尔曼人先后统治过。然而西西里因此也成为了多种文明的交汇点，岛上多样的历史文化建筑更是叹为惊人！ 在这个地中海上最大的岛屿，你可以尽情地放纵自己。无论是在黑手党的老巢巴勒莫寻找曾经“黑暗”的蛛丝马迹，还是在风景如画的陶尔米纳放彻底地拥抱自然，亦或是在恬静小镇锡拉库萨找寻梦中的玛莲娜，你都会经历一场前所未有的美妙的旅程。
