# -------------------------------
# 
# 公共设置
#
# -------------------------------

# 站点设置
title: Kinddom
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.kinddom.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_nav: "#666666" #"#FF3333" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"



# -------------------------------
# 
# 联系方式设置
#
# -------------------------------

# 主页的格言
aphorism: “每一天，每一年，都可以是新的起跑线”

# 社交链接
social:
  - title: facebook
    url:
  - title: twitter
    url:
#  - title: dribbble
#    url:
#  - title: instagram
#    url: 
#  - title: tumblr
#    url: 

# 地址信息
address:
  - lines: 
    - Foshan, Guangdong Province

tel: 15989952520
#email: yaphetcat@gmail.com



# -------------------------------
# 
# 基础数据设置
#
# -------------------------------

# 产品简介
products:
#  - name: Rayfun 子供 女の子 ガールズ ドレス キッズドレス フォーマル ピアノ 演奏会 発表会 結婚式 入園式 コンサート ハロウィン holloween お姫様 プリンセス Princess 洋服 895718
#    img: kinddom_0001.jpg
#    url: "http://www.amazon.co.jp/Rayfun-%E3%82%AD%E3%83%83%E3%82%BA%E3%83%89%E3%83%AC%E3%82%B9-holloween-Princess-895718-x/dp/B00VLAVTGM/ref=sr_1_31?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-31"
#    text: 
#      - ウエディングドレスや高級ドレスを多くご覧いただいた方にはおわかり頂ける上質の子供ドレスです
#      - お子様のデリケートな部分に触れる部分は綿混の総裏地付きです。お肌の弱いお子様にも安心です。
#      - サイズ：商品の説明にご参考してください
#      - 素材とデザインの美しさでお嬢様が着こなすのに相応しいワンピースです
#      - お手頃価格で、特別な日にふさわしい華やかさ?かわいさを演出するドレス
  - name: Wolfteeth® 5 Watt Q5 Mini LED Flashlight; Torch for Riding, Camping, Hiking, Hunting; Adjustable Focus Self-defense Tactical Flashlight; Wear Resistant Finish (Battery Not Included) (Black)
    img: wolfteeth_0001.jpg
  - name: Wolfteeth® 5 Watt Q5 led Flashlight Torch Adjustable Focus Light Lamp(black)
    img: wolfteeth_0002.jpg
  - name: Wolfteeth® 5 Watt Q5 LED Flashlight;Torch for Riding, Camping, Hiking, Hunting; Adjustable Focus Self-defense Tactical Flashlight; Wear Resistant Finish (Battery Not Included) (black)
    img: wolfteeth_0003.jpg
  - name: Wolfteeth® 10 Watt T6 Mini LED Flashlight; Torch for Riding, Camping, Hiking, Hunting; Adjustable Focus Self-defense Tactical Flashlight; Wear Resistant Finish (Battery Not Included) (Black)
    img: wolfteeth_0004.jpg
  - name: Wolfteeth® Bright LED Flashlight; 3 Modes Adjustable Focus Lighting Lamp Flashlight Torch (Gold)
    img: wolfteeth_0005.jpg
  - name: Wolfteeth® T6 10 Watt Led Flashlight; Zoom Self-defense Brigh Flashlight; Long-range Rechargeable Torch (Copper) 
    img: wolfteeth_0006.jpg

# 友情链接
clients:
  - name: amazon_uk
    img: amazon_uk.png
    url: http://www.amazon.co.uk/shops/A3NVU9AA0XWIL
  - name: amazon_jp
    img: amazon_jp.jpg
    url: http://www.amazon.co.jp/s?marketplaceID=A1VC38T7YXB528&me=A1UNGCFEG6Q6NN&merchant=A1UNGCFEG6Q6NN&redirect=true

# 关于我们
about: "Copyright Wolfteeth 2015"

# 品牌故事
brandStory: "We are a passionate and innovative global organisation who put customer satisfaction and experience at the forefront of our vision.Wolfteeth has dedicated staff across three continents that are constantly in pursuit of the latest technologies and innovations to ensure that our customers receive the very best experience. We dont believe in a one-and-done transaction but aim to develop long-term valued customers who hold us in as high regard as we hold them. With this in mind, we source only the very best in top quality materials to ensure that our customers are 100% satisfied, 100% of the time."
