# -------------------------------
# 
# 公共设置
#
# -------------------------------

# 站点设置
title: Kinddom
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.kinddom.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_nav: "#666666" #"#FF3333" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"



# -------------------------------
# 
# 联系方式设置
#
# -------------------------------

# 主页的格言
aphorism: “每一天，每一年，都可以是新的起跑线”

# 社交链接
social:
  - title: facebook
    url:
  - title: twitter
    url:
#  - title: dribbble
#    url:
#  - title: instagram
#    url: 
#  - title: tumblr
#    url: 

# 地址信息
address:
  - lines: 
    - Foshan, Guangdong Province

tel: 15989952520
#email: yaphetcat@gmail.com



# -------------------------------
# 
# 基础数据设置
#
# -------------------------------

# 产品简介
products:
  - name: Rayfun 子供 女の子 ガールズ ドレス キッズドレス フォーマル ピアノ 演奏会 発表会 結婚式 入園式 コンサート ハロウィン holloween お姫様 プリンセス Princess 洋服 895718
    img: kinddom_0001.jpg
    url: "http://www.amazon.co.jp/Rayfun-%E3%82%AD%E3%83%83%E3%82%BA%E3%83%89%E3%83%AC%E3%82%B9-holloween-Princess-895718-x/dp/B00VLAVTGM/ref=sr_1_31?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-31"
    text: 
      - ウエディングドレスや高級ドレスを多くご覧いただいた方にはおわかり頂ける上質の子供ドレスです
      - お子様のデリケートな部分に触れる部分は綿混の総裏地付きです。お肌の弱いお子様にも安心です。
      - サイズ：商品の説明にご参考してください
      - 素材とデザインの美しさでお嬢様が着こなすのに相応しいワンピースです
      - お手頃価格で、特別な日にふさわしい華やかさ?かわいさを演出するドレス
  - name: Rayfun秋冬女子ども服　ロングセクション防風軽薄保温ウェスト締める　毛襟 クリスマス　羽　アヒルの綿毛　子供服　綿服コート　ダウンジャケット1501120
    img: kinddom_0002.jpg
    url: "http://www.amazon.co.jp/Rayfun-Rayfun%E7%A7%8B%E5%86%AC%E5%A5%B3%E5%AD%90%E3%81%A9%E3%82%82%E6%9C%8D%E3%80%80%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BB%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E9%98%B2%E9%A2%A8%E8%BB%BD%E8%96%84%E4%BF%9D%E6%B8%A9%E3%82%A6%E3%82%A7%E3%82%B9%E3%83%88%E7%B7%A0%E3%82%81%E3%82%8B%E3%80%80%E6%AF%9B%E8%A5%9F-%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%9E%E3%82%B9%E3%80%80%E7%BE%BD%E3%80%80%E3%82%A2%E3%83%92%E3%83%AB%E3%81%AE%E7%B6%BF%E6%AF%9B%E3%80%80%E5%AD%90%E4%BE%9B%E6%9C%8D%E3%80%80%E7%B6%BF%E6%9C%8D%E3%82%B3%E3%83%BC%E3%83%88%E3%80%80%E3%83%80%E3%82%A6%E3%83%B3%E3%82%B8%E3%83%A3%E3%82%B1%E3%83%83%E3%83%881501120-130-%E3%83%80%E3%83%BC%E3%82%AF%E3%83%AC%E3%83%83%E3%83%89/dp/B015FPO7QC/ref=sr_1_38?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-38"
    text: 
      - 良質の素材を使い、防風で柔らかく、保温で毛が抜けません。
      - 念入りに仕立てて、立体裁縫、ラインが滑らかで、お嬢様に快適に着用していただきます。
      - 選りすぐりの最上段のダウンフェザーで、ダウンが大きく、ふわふわして活力があり、ダウンの含有量が90％にいたって、軽薄でも暖かいです。
      - 細かいところまで丁寧に仕立ててあります。裾がゴムひもにパイピングデザインで、ダウンが全体的に充実に見えて、寒い風にしっかり防御します。
      - エコな素材で、プロの認証、Rayfunの出品に見定めましょう。
  - name: Rayfun 36+5 LEDワークライト作業灯（フック＆マグネットスタンド付）屋外作業にも便利！
    img: kinddom_0003.jpg
    url: "http://www.amazon.co.jp/Rayfun-7192-36-5-LED%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%A4%E3%83%88%E4%BD%9C%E6%A5%AD%E7%81%AF%EF%BC%88%E3%83%95%E3%83%83%E3%82%AF%EF%BC%86%E3%83%9E%E3%82%B0%E3%83%8D%E3%83%83%E3%83%88%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%E4%BB%98%EF%BC%89%E5%B1%8B%E5%A4%96%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%82%82%E4%BE%BF%E5%88%A9%EF%BC%81/dp/B014KJIT9A/ref=sr_1_28?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-28"
    text: 
      - 材質： ABS+PS、使用電池： 単3形乾電池×3本(電池別売)。
      - 全光束(Lm)： (先端)20～25、(側面)120～150
      - 注意： ※LED球は交換できません。 ※電池は付属しておりません。　●LED寿命(時間)： 100000
      - 点灯方式： 1.ボタンを1回押すと側面の36個のLED点灯 2.ボタンを2回押すと先端の5個のLED点灯
      - 用途： キャンプ・アウトドア、災害時の非常ライト、製造ライン 自動車整備、工事現場、倉庫作業、トラック荷台作業などに
  - name: イーエフイーEFE　こどもドレス　女の子　スパンコール　花　結婚式　ページェントプロムボールドレス　100　110　120　130　140　150　160
    img: kinddom_0004.jpg
    url: "http://www.amazon.co.jp/EFE-%E3%82%A4%E3%83%BC%E3%82%A8%E3%83%95%E3%82%A4%E3%83%BC-%E3%82%A4%E3%83%BC%E3%82%A8%E3%83%95%E3%82%A4%E3%83%BCEFE%E3%80%80%E3%81%93%E3%81%A9%E3%82%82%E3%83%89%E3%83%AC%E3%82%B9%E3%80%80%E5%A5%B3%E3%81%AE%E5%AD%90%E3%80%80%E3%82%B9%E3%83%91%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%AB%E3%80%80%E8%8A%B1%E3%80%80%E7%B5%90%E5%A9%9A%E5%BC%8F%E3%80%80%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%83%97%E3%83%AD%E3%83%A0%E3%83%9C%E3%83%BC%E3%83%AB%E3%83%89%E3%83%AC%E3%82%B9%E3%80%80100%E3%80%80110%E3%80%80120%E3%80%80130%E3%80%80140%E3%80%80150%E3%80%80160-%E3%82%B7%E3%83%A3%E3%83%B3%E3%83%91%E3%83%B3-%E4%B8%A6%E8%A1%8C%E8%BC%B8%E5%85%A5%E5%93%81/dp/B010CLGRFS/ref=sr_1_39?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-39"
    text: 
      - 素材：ポリエステル+サテン
      - 色： シルバー、 ピンク、シャンパン
      - サイズ：100、110、120、130、140、150、160
      - 購入前に製品の説明で詳細サイズ表をご参照ください。
  - name: Rayfun 子供 女の子 ガールズ ドレス キッズドレス フォーマル ピアノ 演奏会 発表会 結婚式 入園式 コンサート ハロウィン holloween お姫様 プリンセス Princess 洋服 865010
    img: kinddom_0005.jpg
    url: "http://www.amazon.co.jp/Rayfun-%E3%82%AD%E3%83%83%E3%82%BA%E3%83%89%E3%83%AC%E3%82%B9-holloween-Princess-865010/dp/B00VLXL5B8/ref=sr_1_43?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-43"
    text: 
      - ウエディングドレスや高級ドレスを多くご覧いただいた方にはおわかり頂ける上質の子供ドレスです
      - お子様のデリケートな部分に触れる部分は綿混の総裏地付きです。お肌の弱いお子様にも安心です。
      - サイズ：商品の説明にご参考してください
      - 素材とデザインの美しさでお嬢様が着こなすのに相応しいワンピースです
      - お手頃価格で、特別な日にふさわしい華やかさ?かわいさを演出するドレス

# 友情链接
clients:
  - name: amazon_uk
    img: amazon_uk.png
    url: http://www.amazon.co.uk/shops/A3NVU9AA0XWIL
  - name: amazon_jp
    img: amazon_jp.jpg
    url: http://www.amazon.co.jp/s?marketplaceID=A1VC38T7YXB528&me=A1UNGCFEG6Q6NN&merchant=A1UNGCFEG6Q6NN&redirect=true

# 关于我们
about: "Copyright Wolfteeth 2015"

# 品牌故事
brandStory: "We are a passionate and innovative global organisation who put customer satisfaction and experience at the forefront of our vision.Wolfteeth has dedicated staff across three continents that are constantly in pursuit of the latest technologies and innovations to ensure that our customers receive the very best experience. We dont believe in a one-and-done transaction but aim to develop long-term valued customers who hold us in as high regard as we hold them. With this in mind, we source only the very best in top quality materials to ensure that our customers are 100% satisfied, 100% of the time."
