# -------------------------------
# 
# 公共设置
#
# -------------------------------

# 站点设置
title: Kinddom
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.kinddom.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_nav: "#666666" #"#FF3333" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"



# -------------------------------
# 
# 联系方式设置
#
# -------------------------------

# 主页的格言
aphorism: “每一天，每一年，都可以是新的起跑线”

# 社交链接
social:
  - title: facebook
    url:
  - title: twitter
    url:
#  - title: dribbble
#    url:
#  - title: instagram
#    url: 
#  - title: tumblr
#    url: 

# 地址信息
address:
  - lines: 
    - 广东省, 佛山市
    - 顺德区, 大良镇
email: yaphetcat@gmail.com
tel: 15989952520



# -------------------------------
# 
# 基础数据设置
#
# -------------------------------

# 产品简介
products:
  - name: Rayfun 子供 女の子 ガールズ ドレス キッズドレス フォーマル ピアノ 演奏会 発表会 結婚式 入園式 コンサート ハロウィン holloween お姫様 プリンセス Princess 洋服 895718
    text: サイズと色を選択すると表示されます（ポイントがつかない場合、この項目は消えます）
    img: kinddom_0001.jpg
    url: "http://www.amazon.co.jp/Rayfun-%E3%82%AD%E3%83%83%E3%82%BA%E3%83%89%E3%83%AC%E3%82%B9-holloween-Princess-895718-x/dp/B00VLAVTGM/ref=sr_1_31?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-31"
  - name: Rayfun秋冬女子ども服　ロングセクション防風軽薄保温ウェスト締める　毛襟 クリスマス　羽　アヒルの綿毛　子供服　綿服コート　ダウンジャケット1501120
    text: サイズと色を選択すると表示されます（ポイントがつかない場合、この項目は消えます）
    img: kinddom_0002.jpg
    url: "http://www.amazon.co.jp/Rayfun-Rayfun%E7%A7%8B%E5%86%AC%E5%A5%B3%E5%AD%90%E3%81%A9%E3%82%82%E6%9C%8D%E3%80%80%E3%83%AD%E3%83%B3%E3%82%B0%E3%82%BB%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E9%98%B2%E9%A2%A8%E8%BB%BD%E8%96%84%E4%BF%9D%E6%B8%A9%E3%82%A6%E3%82%A7%E3%82%B9%E3%83%88%E7%B7%A0%E3%82%81%E3%82%8B%E3%80%80%E6%AF%9B%E8%A5%9F-%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%9E%E3%82%B9%E3%80%80%E7%BE%BD%E3%80%80%E3%82%A2%E3%83%92%E3%83%AB%E3%81%AE%E7%B6%BF%E6%AF%9B%E3%80%80%E5%AD%90%E4%BE%9B%E6%9C%8D%E3%80%80%E7%B6%BF%E6%9C%8D%E3%82%B3%E3%83%BC%E3%83%88%E3%80%80%E3%83%80%E3%82%A6%E3%83%B3%E3%82%B8%E3%83%A3%E3%82%B1%E3%83%83%E3%83%881501120-130-%E3%83%80%E3%83%BC%E3%82%AF%E3%83%AC%E3%83%83%E3%83%89/dp/B015FPO7QC/ref=sr_1_38?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-38"
  - name: Rayfun 36+5 LEDワークライト作業灯（フック＆マグネットスタンド付）屋外作業にも便利！
    text: この商品は、Rayfun が販売、発送します。 返品については出品者のリンクからご確認ください。 この出品商品にはコンビニ・ATM・ネットバンキング・電子マネー払いが利用できます
    img: kinddom_0003.jpg
    url: "http://www.amazon.co.jp/Rayfun-7192-36-5-LED%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%A4%E3%83%88%E4%BD%9C%E6%A5%AD%E7%81%AF%EF%BC%88%E3%83%95%E3%83%83%E3%82%AF%EF%BC%86%E3%83%9E%E3%82%B0%E3%83%8D%E3%83%83%E3%83%88%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%E4%BB%98%EF%BC%89%E5%B1%8B%E5%A4%96%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%82%82%E4%BE%BF%E5%88%A9%EF%BC%81/dp/B014KJIT9A/ref=sr_1_28?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-28"
  - name: イーエフイーEFE　こどもドレス　女の子　スパンコール　花　結婚式　ページェントプロムボールドレス　100　110　120　130　140　150　160
    text: サイズと色を選択すると表示されます（ポイントがつかない場合、この項目は消えます）
    img: kinddom_0004.jpg
    url: "http://www.amazon.co.jp/EFE-%E3%82%A4%E3%83%BC%E3%82%A8%E3%83%95%E3%82%A4%E3%83%BC-%E3%82%A4%E3%83%BC%E3%82%A8%E3%83%95%E3%82%A4%E3%83%BCEFE%E3%80%80%E3%81%93%E3%81%A9%E3%82%82%E3%83%89%E3%83%AC%E3%82%B9%E3%80%80%E5%A5%B3%E3%81%AE%E5%AD%90%E3%80%80%E3%82%B9%E3%83%91%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%AB%E3%80%80%E8%8A%B1%E3%80%80%E7%B5%90%E5%A9%9A%E5%BC%8F%E3%80%80%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%A7%E3%83%B3%E3%83%88%E3%83%97%E3%83%AD%E3%83%A0%E3%83%9C%E3%83%BC%E3%83%AB%E3%83%89%E3%83%AC%E3%82%B9%E3%80%80100%E3%80%80110%E3%80%80120%E3%80%80130%E3%80%80140%E3%80%80150%E3%80%80160-%E3%82%B7%E3%83%A3%E3%83%B3%E3%83%91%E3%83%B3-%E4%B8%A6%E8%A1%8C%E8%BC%B8%E5%85%A5%E5%93%81/dp/B010CLGRFS/ref=sr_1_39?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-39"
  - name: Rayfun 子供 女の子 ガールズ ドレス キッズドレス フォーマル ピアノ 演奏会 発表会 結婚式 入園式 コンサート ハロウィン holloween お姫様 プリンセス Princess 洋服 865010
    text: サイズと色を選択すると表示されます（ポイントがつかない場合、この項目は消えます）
    img: kinddom_0005.jpg
    url: "http://www.amazon.co.jp/Rayfun-%E3%82%AD%E3%83%83%E3%82%BA%E3%83%89%E3%83%AC%E3%82%B9-holloween-Princess-865010/dp/B00VLXL5B8/ref=sr_1_43?m=A1UNGCFEG6Q6NN&s=merchant-items&ie=UTF8&qid=1443871952&sr=1-43"

# 友情链接
clients:
  - name: amazon
    img: client01.png
    url: http://www.amazon.co.uk/shops/A3NVU9AA0XWIL
  - name: wish
    img: client02.png
    url: http://www.wish.com

# 关于我们
about: "Kinddom是一家负责对外贸易的产品介绍网站, 期待与您合作."

# 品牌故事
brandStory: “如果不去西西里，就像没有到过意大利，因为在西西里你才能找到意大利的美丽之源。” 西西里岛在历史上命运多舛，曾经被希腊人、西班牙人、阿拉伯人和诺尔曼人先后统治过。然而西西里因此也成为了多种文明的交汇点，岛上多样的历史文化建筑更是叹为惊人！ 在这个地中海上最大的岛屿，你可以尽情地放纵自己。无论是在黑手党的老巢巴勒莫寻找曾经“黑暗”的蛛丝马迹，还是在风景如画的陶尔米纳放彻底地拥抱自然，亦或是在恬静小镇锡拉库萨找寻梦中的玛莲娜，你都会经历一场前所未有的美妙的旅程。
